/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) inequality_constraint_function_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[76] = {72, 1, 0, 72, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s3[20] = {0, 3, 6, 9, 12, 15, 18, 21, 24, 26, 28, 30, 32, 34, 36, 38, 40, 41, 42, 43};
static const casadi_int casadi_s4[16] = {2, 5, 8, 11, 14, 17, 20, 23, 25, 27, 29, 31, 33, 35, 37, 39};
static const casadi_int casadi_s5[67] = {72, 20, 0, 3, 6, 9, 12, 15, 18, 21, 24, 26, 28, 30, 32, 34, 36, 38, 40, 41, 42, 43, 44, 63, 64, 65, 63, 64, 65, 63, 64, 65, 63, 64, 65, 69, 70, 71, 69, 70, 71, 69, 70, 71, 69, 70, 71, 62, 65, 62, 65, 62, 65, 62, 65, 68, 71, 68, 71, 68, 71, 68, 71, 60, 61, 66, 67};
static const casadi_int casadi_s6[119] = {20, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 6, 10, 14, 22, 23, 24, 28, 32, 36, 44, 16, 17, 8, 9, 10, 11, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 8, 9, 10, 11, 18, 19, 12, 13, 14, 15, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 12, 13, 14, 15};

/* b_ineq_function:(i0[72],i1[2])->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+30, w20, w21, w22, *w23=w+35;
  /* #0: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+60 : 0, 12, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #3: @1 = (@1+@2) */
  w1 += w2;
  /* #4: @2 = 0.6 */
  w2 = 5.9999999999999998e-01;
  /* #5: @3 = @0[5] */
  for (rr=(&w3), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #6: @2 = (@2*@3) */
  w2 *= w3;
  /* #7: @1 = (@1-@2) */
  w1 -= w2;
  /* #8: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #9: @3 = @0[3] */
  for (rr=(&w3), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #10: @2 = (@2-@3) */
  w2 -= w3;
  /* #11: @3 = 0.6 */
  w3 = 5.9999999999999998e-01;
  /* #12: @4 = @0[5] */
  for (rr=(&w4), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #13: @3 = (@3*@4) */
  w3 *= w4;
  /* #14: @2 = (@2-@3) */
  w2 -= w3;
  /* #15: @3 = @0[3] */
  for (rr=(&w3), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #16: @4 = @0[4] */
  for (rr=(&w4), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #17: @3 = (@3-@4) */
  w3 -= w4;
  /* #18: @4 = 0.6 */
  w4 = 5.9999999999999998e-01;
  /* #19: @5 = @0[5] */
  for (rr=(&w5), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #20: @4 = (@4*@5) */
  w4 *= w5;
  /* #21: @3 = (@3-@4) */
  w3 -= w4;
  /* #22: @4 = @0[3] */
  for (rr=(&w4), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #23: @4 = (-@4) */
  w4 = (- w4 );
  /* #24: @5 = @0[4] */
  for (rr=(&w5), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #25: @4 = (@4-@5) */
  w4 -= w5;
  /* #26: @5 = 0.6 */
  w5 = 5.9999999999999998e-01;
  /* #27: @6 = @0[5] */
  for (rr=(&w6), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #28: @5 = (@5*@6) */
  w5 *= w6;
  /* #29: @4 = (@4-@5) */
  w4 -= w5;
  /* #30: @5 = @0[9] */
  for (rr=(&w5), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #31: @6 = @0[10] */
  for (rr=(&w6), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #32: @5 = (@5+@6) */
  w5 += w6;
  /* #33: @6 = 0.6 */
  w6 = 5.9999999999999998e-01;
  /* #34: @7 = @0[11] */
  for (rr=(&w7), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #35: @6 = (@6*@7) */
  w6 *= w7;
  /* #36: @5 = (@5-@6) */
  w5 -= w6;
  /* #37: @6 = @0[10] */
  for (rr=(&w6), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #38: @7 = @0[9] */
  for (rr=(&w7), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #39: @6 = (@6-@7) */
  w6 -= w7;
  /* #40: @7 = 0.6 */
  w7 = 5.9999999999999998e-01;
  /* #41: @8 = @0[11] */
  for (rr=(&w8), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #42: @7 = (@7*@8) */
  w7 *= w8;
  /* #43: @6 = (@6-@7) */
  w6 -= w7;
  /* #44: @7 = @0[9] */
  for (rr=(&w7), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #45: @8 = @0[10] */
  for (rr=(&w8), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #46: @7 = (@7-@8) */
  w7 -= w8;
  /* #47: @8 = 0.6 */
  w8 = 5.9999999999999998e-01;
  /* #48: @9 = @0[11] */
  for (rr=(&w9), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #49: @8 = (@8*@9) */
  w8 *= w9;
  /* #50: @7 = (@7-@8) */
  w7 -= w8;
  /* #51: @8 = @0[9] */
  for (rr=(&w8), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #52: @8 = (-@8) */
  w8 = (- w8 );
  /* #53: @9 = @0[10] */
  for (rr=(&w9), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #54: @8 = (@8-@9) */
  w8 -= w9;
  /* #55: @9 = 0.6 */
  w9 = 5.9999999999999998e-01;
  /* #56: @10 = @0[11] */
  for (rr=(&w10), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #57: @9 = (@9*@10) */
  w9 *= w10;
  /* #58: @8 = (@8-@9) */
  w8 -= w9;
  /* #59: @9 = @0[2] */
  for (rr=(&w9), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #60: @10 = 0.0075 */
  w10 = 7.4999999999999997e-03;
  /* #61: @11 = @0[5] */
  for (rr=(&w11), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #62: @10 = (@10*@11) */
  w10 *= w11;
  /* #63: @9 = (@9-@10) */
  w9 -= w10;
  /* #64: @10 = @0[2] */
  for (rr=(&w10), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #65: @10 = (-@10) */
  w10 = (- w10 );
  /* #66: @11 = 0.0075 */
  w11 = 7.4999999999999997e-03;
  /* #67: @12 = @0[5] */
  for (rr=(&w12), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #68: @11 = (@11*@12) */
  w11 *= w12;
  /* #69: @10 = (@10-@11) */
  w10 -= w11;
  /* #70: @11 = @0[2] */
  for (rr=(&w11), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #71: @12 = 0.015 */
  w12 = 1.4999999999999999e-02;
  /* #72: @13 = @0[5] */
  for (rr=(&w13), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #73: @12 = (@12*@13) */
  w12 *= w13;
  /* #74: @11 = (@11-@12) */
  w11 -= w12;
  /* #75: @12 = @0[2] */
  for (rr=(&w12), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #76: @12 = (-@12) */
  w12 = (- w12 );
  /* #77: @13 = 0.015 */
  w13 = 1.4999999999999999e-02;
  /* #78: @14 = @0[5] */
  for (rr=(&w14), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #79: @13 = (@13*@14) */
  w13 *= w14;
  /* #80: @12 = (@12-@13) */
  w12 -= w13;
  /* #81: @13 = @0[8] */
  for (rr=(&w13), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #82: @14 = 0.0075 */
  w14 = 7.4999999999999997e-03;
  /* #83: @15 = @0[11] */
  for (rr=(&w15), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #84: @14 = (@14*@15) */
  w14 *= w15;
  /* #85: @13 = (@13-@14) */
  w13 -= w14;
  /* #86: @14 = @0[8] */
  for (rr=(&w14), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #87: @14 = (-@14) */
  w14 = (- w14 );
  /* #88: @15 = 0.0075 */
  w15 = 7.4999999999999997e-03;
  /* #89: @16 = @0[11] */
  for (rr=(&w16), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #90: @15 = (@15*@16) */
  w15 *= w16;
  /* #91: @14 = (@14-@15) */
  w14 -= w15;
  /* #92: @15 = @0[8] */
  for (rr=(&w15), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #93: @16 = 0.015 */
  w16 = 1.4999999999999999e-02;
  /* #94: @17 = @0[11] */
  for (rr=(&w17), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #95: @16 = (@16*@17) */
  w16 *= w17;
  /* #96: @15 = (@15-@16) */
  w15 -= w16;
  /* #97: @16 = @0[8] */
  for (rr=(&w16), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #98: @16 = (-@16) */
  w16 = (- w16 );
  /* #99: @17 = 0.015 */
  w17 = 1.4999999999999999e-02;
  /* #100: @18 = @0[11] */
  for (rr=(&w18), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #101: @17 = (@17*@18) */
  w17 *= w18;
  /* #102: @16 = (@16-@17) */
  w16 -= w17;
  /* #103: @17 = @0[0] */
  for (rr=(&w17), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #104: @19 = input[1][0] */
  casadi_copy(arg[1], 2, w19);
  /* #105: @18 = @19[0] */
  for (rr=(&w18), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #106: @17 = (@17/@18) */
  w17 /= w18;
  /* #107: @18 = 0.0125 */
  w18 = 1.2500000000000001e-02;
  /* #108: @17 = (@17-@18) */
  w17 -= w18;
  /* #109: @18 = @0[1] */
  for (rr=(&w18), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #110: @20 = @19[0] */
  for (rr=(&w20), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #111: @18 = (@18/@20) */
  w18 /= w20;
  /* #112: @20 = 0.025 */
  w20 = 2.5000000000000001e-02;
  /* #113: @18 = (@18-@20) */
  w18 -= w20;
  /* #114: @20 = @0[6] */
  for (rr=(&w20), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #115: @21 = @19[1] */
  for (rr=(&w21), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #116: @20 = (@20/@21) */
  w20 /= w21;
  /* #117: @21 = 0.0125 */
  w21 = 1.2500000000000001e-02;
  /* #118: @20 = (@20-@21) */
  w20 -= w21;
  /* #119: @21 = @0[7] */
  for (rr=(&w21), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #120: @22 = @19[1] */
  for (rr=(&w22), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #121: @21 = (@21/@22) */
  w21 /= w22;
  /* #122: @22 = 0.025 */
  w22 = 2.5000000000000001e-02;
  /* #123: @21 = (@21-@22) */
  w21 -= w22;
  /* #124: @23 = vertcat(@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @20, @21) */
  rr=w23;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w21;
  /* #125: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<20; ++i) *rr++ = (- *cs++ );
  /* #126: output[0][0] = @23 */
  casadi_copy(w23, 20, res[0]);
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int b_ineq_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int b_ineq_function_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int b_ineq_function_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void b_ineq_function_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int b_ineq_function_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void b_ineq_function_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void b_ineq_function_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void b_ineq_function_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int b_ineq_function_n_in(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int b_ineq_function_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real b_ineq_function_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* b_ineq_function_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* b_ineq_function_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* b_ineq_function_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* b_ineq_function_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int b_ineq_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 55;
  return 0;
}

/* A_ineq_function:(i0[72],i1[2])->(o0[20x72,44nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real *w0=w+0, *w1=w+44, *w2=w+112, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+137, w21, w22, w23, w24, *w25=w+143, *w26=w+163, *w39=w+165, *w40=w+173, *w41=w+189, *w42=w+205;
  /* #0: @0 = zeros(72x20,44nz) */
  casadi_clear(w0, 44);
  /* #1: @1 = ones(72x1,68nz) */
  casadi_fill(w1, 68, 1.);
  /* #2: {NULL, NULL, NULL, @2} = vertsplit(@1) */
  casadi_copy(w1+60, 8, w2);
  /* #3: @3 = @2[3] */
  for (rr=(&w3), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #4: @4 = @2[3] */
  for (rr=(&w4), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #5: @4 = (-@4) */
  w4 = (- w4 );
  /* #6: @5 = @2[3] */
  for (rr=(&w5), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #7: @6 = @2[3] */
  for (rr=(&w6), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #8: @6 = (-@6) */
  w6 = (- w6 );
  /* #9: @7 = @2[7] */
  for (rr=(&w7), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #10: @8 = @2[7] */
  for (rr=(&w8), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #11: @8 = (-@8) */
  w8 = (- w8 );
  /* #12: @9 = @2[7] */
  for (rr=(&w9), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #13: @10 = @2[7] */
  for (rr=(&w10), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #14: @10 = (-@10) */
  w10 = (- w10 );
  /* #15: @11 = @2[2] */
  for (rr=(&w11), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #16: @12 = @2[2] */
  for (rr=(&w12), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #17: @12 = (-@12) */
  w12 = (- w12 );
  /* #18: @13 = @2[2] */
  for (rr=(&w13), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #19: @14 = @2[2] */
  for (rr=(&w14), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #20: @14 = (-@14) */
  w14 = (- w14 );
  /* #21: @15 = @2[6] */
  for (rr=(&w15), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #22: @16 = @2[6] */
  for (rr=(&w16), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #23: @16 = (-@16) */
  w16 = (- w16 );
  /* #24: @17 = @2[6] */
  for (rr=(&w17), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #25: @18 = @2[6] */
  for (rr=(&w18), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #26: @18 = (-@18) */
  w18 = (- w18 );
  /* #27: @19 = @2[0] */
  for (rr=(&w19), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #28: @20 = input[1][0] */
  casadi_copy(arg[1], 2, w20);
  /* #29: @21 = @20[0] */
  for (rr=(&w21), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #30: @19 = (@19/@21) */
  w19 /= w21;
  /* #31: @21 = @2[1] */
  for (rr=(&w21), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #32: @22 = @20[0] */
  for (rr=(&w22), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #33: @21 = (@21/@22) */
  w21 /= w22;
  /* #34: @22 = @2[4] */
  for (rr=(&w22), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #35: @23 = @20[1] */
  for (rr=(&w23), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #36: @22 = (@22/@23) */
  w22 /= w23;
  /* #37: @23 = @2[5] */
  for (rr=(&w23), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #38: @24 = @20[1] */
  for (rr=(&w24), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #39: @23 = (@23/@24) */
  w23 /= w24;
  /* #40: @25 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @21, @22, @23) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #41: (@0[0, 3, 6, 9, 12, 15, 18, 21, 24, 26, 28, 30, 32, 34, 36, 38, 40, 41, 42, 43] = @25) */
  for (cii=casadi_s3, rr=w0, ss=w25; cii!=casadi_s3+20; ++cii, ++ss) rr[*cii] = *ss;
  /* #42: @20 = ones(72x1,2nz) */
  casadi_fill(w20, 2, 1.);
  /* #43: {NULL, NULL, NULL, @26} = vertsplit(@20) */
  casadi_copy(w20, 2, w26);
  /* #44: @3 = @26[0] */
  for (rr=(&w3), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #45: @4 = @26[0] */
  for (rr=(&w4), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #46: @5 = @26[0] */
  for (rr=(&w5), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #47: @5 = (-@5) */
  w5 = (- w5 );
  /* #48: @6 = @26[0] */
  for (rr=(&w6), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  /* #49: @6 = (-@6) */
  w6 = (- w6 );
  /* #50: @7 = @26[1] */
  for (rr=(&w7), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #51: @8 = @26[1] */
  for (rr=(&w8), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #52: @9 = @26[1] */
  for (rr=(&w9), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #53: @9 = (-@9) */
  w9 = (- w9 );
  /* #54: @10 = @26[1] */
  for (rr=(&w10), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #55: @10 = (-@10) */
  w10 = (- w10 );
  /* #56: @27 = 00 */
  /* #57: @28 = 00 */
  /* #58: @29 = 00 */
  /* #59: @30 = 00 */
  /* #60: @31 = 00 */
  /* #61: @32 = 00 */
  /* #62: @33 = 00 */
  /* #63: @34 = 00 */
  /* #64: @35 = 00 */
  /* #65: @36 = 00 */
  /* #66: @37 = 00 */
  /* #67: @38 = 00 */
  /* #68: @2 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38) */
  rr=w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #69: @39 = @2[:8] */
  for (rr=w39, ss=w2+0; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #70: (@0[1:25:3] = @39) */
  for (rr=w0+1, ss=w39; rr!=w0+25; rr+=3) *rr = *ss++;
  /* #71: @3 = 0.6 */
  w3 = 5.9999999999999998e-01;
  /* #72: @26 = ones(72x1,2nz) */
  casadi_fill(w26, 2, 1.);
  /* #73: {NULL, NULL, NULL, @20} = vertsplit(@26) */
  casadi_copy(w26, 2, w20);
  /* #74: @4 = @20[0] */
  for (rr=(&w4), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #75: @3 = (@3*@4) */
  w3 *= w4;
  /* #76: @3 = (-@3) */
  w3 = (- w3 );
  /* #77: @4 = 0.6 */
  w4 = 5.9999999999999998e-01;
  /* #78: @5 = @20[0] */
  for (rr=(&w5), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #79: @4 = (@4*@5) */
  w4 *= w5;
  /* #80: @4 = (-@4) */
  w4 = (- w4 );
  /* #81: @5 = 0.6 */
  w5 = 5.9999999999999998e-01;
  /* #82: @6 = @20[0] */
  for (rr=(&w6), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #83: @5 = (@5*@6) */
  w5 *= w6;
  /* #84: @5 = (-@5) */
  w5 = (- w5 );
  /* #85: @6 = 0.6 */
  w6 = 5.9999999999999998e-01;
  /* #86: @7 = @20[0] */
  for (rr=(&w7), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #87: @6 = (@6*@7) */
  w6 *= w7;
  /* #88: @6 = (-@6) */
  w6 = (- w6 );
  /* #89: @7 = 0.6 */
  w7 = 5.9999999999999998e-01;
  /* #90: @8 = @20[1] */
  for (rr=(&w8), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #91: @7 = (@7*@8) */
  w7 *= w8;
  /* #92: @7 = (-@7) */
  w7 = (- w7 );
  /* #93: @8 = 0.6 */
  w8 = 5.9999999999999998e-01;
  /* #94: @9 = @20[1] */
  for (rr=(&w9), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #95: @8 = (@8*@9) */
  w8 *= w9;
  /* #96: @8 = (-@8) */
  w8 = (- w8 );
  /* #97: @9 = 0.6 */
  w9 = 5.9999999999999998e-01;
  /* #98: @10 = @20[1] */
  for (rr=(&w10), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #99: @9 = (@9*@10) */
  w9 *= w10;
  /* #100: @9 = (-@9) */
  w9 = (- w9 );
  /* #101: @10 = 0.6 */
  w10 = 5.9999999999999998e-01;
  /* #102: @11 = @20[1] */
  for (rr=(&w11), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #103: @10 = (@10*@11) */
  w10 *= w11;
  /* #104: @10 = (-@10) */
  w10 = (- w10 );
  /* #105: @11 = 0.0075 */
  w11 = 7.4999999999999997e-03;
  /* #106: @12 = @20[0] */
  for (rr=(&w12), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #107: @11 = (@11*@12) */
  w11 *= w12;
  /* #108: @11 = (-@11) */
  w11 = (- w11 );
  /* #109: @12 = 0.0075 */
  w12 = 7.4999999999999997e-03;
  /* #110: @13 = @20[0] */
  for (rr=(&w13), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #111: @12 = (@12*@13) */
  w12 *= w13;
  /* #112: @12 = (-@12) */
  w12 = (- w12 );
  /* #113: @13 = 0.015 */
  w13 = 1.4999999999999999e-02;
  /* #114: @14 = @20[0] */
  for (rr=(&w14), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #115: @13 = (@13*@14) */
  w13 *= w14;
  /* #116: @13 = (-@13) */
  w13 = (- w13 );
  /* #117: @14 = 0.015 */
  w14 = 1.4999999999999999e-02;
  /* #118: @15 = @20[0] */
  for (rr=(&w15), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #119: @14 = (@14*@15) */
  w14 *= w15;
  /* #120: @14 = (-@14) */
  w14 = (- w14 );
  /* #121: @15 = 0.0075 */
  w15 = 7.4999999999999997e-03;
  /* #122: @16 = @20[1] */
  for (rr=(&w16), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #123: @15 = (@15*@16) */
  w15 *= w16;
  /* #124: @15 = (-@15) */
  w15 = (- w15 );
  /* #125: @16 = 0.0075 */
  w16 = 7.4999999999999997e-03;
  /* #126: @17 = @20[1] */
  for (rr=(&w17), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #127: @16 = (@16*@17) */
  w16 *= w17;
  /* #128: @16 = (-@16) */
  w16 = (- w16 );
  /* #129: @17 = 0.015 */
  w17 = 1.4999999999999999e-02;
  /* #130: @18 = @20[1] */
  for (rr=(&w18), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #131: @17 = (@17*@18) */
  w17 *= w18;
  /* #132: @17 = (-@17) */
  w17 = (- w17 );
  /* #133: @18 = 0.015 */
  w18 = 1.4999999999999999e-02;
  /* #134: @19 = @20[1] */
  for (rr=(&w19), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #135: @18 = (@18*@19) */
  w18 *= w19;
  /* #136: @18 = (-@18) */
  w18 = (- w18 );
  /* #137: @27 = 00 */
  /* #138: @28 = 00 */
  /* #139: @29 = 00 */
  /* #140: @30 = 00 */
  /* #141: @40 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @27, @28, @29, @30) */
  rr=w40;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #142: @41 = @40[:16] */
  for (rr=w41, ss=w40+0; ss!=w40+16; ss+=1) *rr++ = *ss;
  /* #143: (@0[2, 5, 8, 11, 14, 17, 20, 23, 25, 27, 29, 31, 33, 35, 37, 39] = @41) */
  for (cii=casadi_s4, rr=w0, ss=w41; cii!=casadi_s4+16; ++cii, ++ss) rr[*cii] = *ss;
  /* #144: @42 = @0' */
  casadi_trans(w0,casadi_s5, w42, casadi_s6, iw);
  /* #145: output[0][0] = @42 */
  casadi_copy(w42, 44, res[0]);
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int A_ineq_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int A_ineq_function_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int A_ineq_function_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void A_ineq_function_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int A_ineq_function_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void A_ineq_function_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void A_ineq_function_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void A_ineq_function_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int A_ineq_function_n_in(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int A_ineq_function_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real A_ineq_function_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* A_ineq_function_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* A_ineq_function_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* A_ineq_function_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* A_ineq_function_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int A_ineq_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 22;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 73;
  if (sz_w) *sz_w = 249;
  return 0;
}


